### ISSUE TITLE
Revert upgrade to jarkata v3

### ISSUE THREAD

**Issue by otbe** [prisma-capacity/spring-cqs#200]
Some time ago #185 was merged and this seems to break compatibility to Spring Boot 2.X. At least what I understand from https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M1-Release-Notes is that only SB 3.X will fully support v3 (new package names) and work as expected (and also include new hibernate validator version&co)

Reasoning behind this issue is that we're having hard times to get it working at all with the latest version of Spring CQS.
Exceptions like `Caused by: java.lang.ClassNotFoundException: jakarta.validation.Validator` are thrown at runtime.

**Comment by uweschaefer** [comment]
will be re-released as 2.0.6
